import type { Metadata } from 'next'
import { ReactScan } from '@/app/components/ReactScan'
import { inter, playfair, satoshi } from '@/lib/fonts'
import './global.css'

export const metadata: Metadata = {
  title: 'Dr. Madhan Institute of Future',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} ${satoshi.className} ${playfair.variable}`}
      style={{ colorScheme: 'light' }}
    >
      <head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
      </head>
      <ReactScan />
      <body className="antialiased">{children}</body>
    </html>
  )
}
