import type { Metadata } from 'next'
import './globals.css'
import { ReactScan } from '@/app/components/ReactScan'
import { inter, satoshi } from '@/lib/fonts'

export const metadata: Metadata = {
  title: 'Dr. Madhan Institute of <Future></Future>',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${inter.className} ${satoshi.className}`}>
      <head>
        <meta charSet="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
      </head>
      <ReactScan />
      <body className="antialiased">{children}</body>
    </html>
  )
}
